server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "visitor"
    password: "123456"
    url: "jdbc:mysql://localhost:3306/book_store?characterEncoding=
    utf-8&useSSL=false&allowPublicKeyRetrieval=true"

mybatis-plus:
  mapper-locations: "classpath:/mappers/*.xml"